[package]
name = "messaging-proto"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
prost.workspace = true
prost-types = "0.13"

[build-dependencies]
prost-build.workspace = true
protoc-bin-vendored = "3.0"
